### ISSUE TITLE
bug(select): Multi-select dropdown selected values aren't removed from options list

### ISSUE THREAD

**Issue by ericwyh** [edcarroll/ng2-semantic-ui#148]
### Bug description:
When selecting values in a sui-multi-select, the selected values aren't removed from the list.
This allows the user to select a value more than once. 

Please let me know if I'm doing something wrong. 

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/fbrOoP?p=preview

### Version of Angular, ng2-semantic-ui, and Semantic UI:
ng2-semantic-ui: 0.8.4

**Comment by edcarroll** [comment]
In order to make the options disappear as expected, you must bind to the `availableOptions` property of the multi select, as follows:

```html
<sui-multi-select [(ngModel)]="selection" [isSearchable]="true" [options]="options" (ngModelChange)="onChange($event)" #select>
  <sui-select-option *ngFor="let option of select.availableOptions" [value]="option">{{option}}</sui-select-option>
</sui-multi-select>
```

Otherwise, the options aren't ever filtered so you can reselect them.

(Note there is a release arriving in a few hours that renames `availableOptions` to `filteredOptions`, though the former will still work but just be deprecated)
