### ISSUE TITLE
No provider for SuiComponentFactory

### ISSUE THREAD

**Issue by mvcoding** [edcarroll/ng2-semantic-ui#160]
### Bug description:

With v0.9.2 i get an error about a missing provider for SuiComponentFactory when i load just individual modules, specifically SuiSelectModule and using sui-multi-select from it, instead of the full SuiModule. Importing SuiUtilityModule makes the error go away but i'm not sure if it is intended this way.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/RiOsIb4uoxAOhW31VX2i?p=preview

Selecting an option throws the error. Import SuiUtilityModule and it goes away.

### Version of Angular, ng2-semantic-ui, and Semantic UI:

- Angular: 4.2.5
- ng2-semantic-ui: 0.9.2
- Semantic UI: 2.2.10

**Comment by edcarroll** [comment]
Good catch, turns out select & modal were missing the module imports after the project reshuffle in this release.

For now, adding `SuiUtilityModule` and `SuiLocalizationModule` whenever you are importing the `SuiSelectModule`, and adding `SuiUtilityModule` whenever you are importing `SuiModalModule` provides a workaround until this goes into a release.

**Comment by edcarroll** [comment]
Fix for this has been merged, will release in the next couple of days.

**Comment by edcarroll** [comment]
`0.9.3` now live with this fix, you can remove references to those extra modules now without any ill effect. Thanks for your patience!
