### ISSUE TITLE
warning : export 'ModalTemplate' was not found in 'ng2-semantic-ui'

### ISSUE THREAD

**Issue by dev-fullstacktechnology** [edcarroll/ng2-semantic-ui#171]
### Bug description: importing ModalTemplate cause warning for 
export 'ModalTemplate' was not found in 'ng2-semantic-ui'

I had this error when I am using template based modal method for dialog.
I am not getting this type of error in plunker so I was putting snapshot of my project code.

![screenshot_1](https://user-images.githubusercontent.com/22045550/28151753-42911480-67ba-11e7-8aaa-1db092394a18.png)

### Version of Angular, ng2-semantic-ui, Semantic UI

Angular: 4.2.2
ng2-semantic-ui: 0.8.2
Semantic UI: 2.2.2

I looked on internet but there is no such answer found for my solution.

Send me a reply if you need any other detail related to issue.

**Comment by sumitridhal** [comment]
I'm getting the same error.

**Comment by edcarroll** [comment]
This is a webpack issue due to the fact that interfaces in Typescript are erased upon compilation.

A workaround (for now) is to make a new file called `modal-template.ts` (or anything you like) that has the contents:

```typescript
import {ModalTemplate} from "ng2-semantic-ui";

export {ModalTemplate};
```

Then whenever you need `ModalTemplate` just import it from this new file (called a barrel).

I'll try to get a fix for this sorted next week, am currently on holiday so a workaround will have to do for now :)

**Comment by sumitridhal** [comment]
@edcarroll Thanks a lot :+1:

**Comment by dev-fullstacktechnology** [comment]
Thanks for solutions. I will check for that solution.

**Comment by edcarroll** [comment]
@dev-fullstacktechnology apologies, can't work out what you mean by your last message, is there a specific style of multi select not working?

**Comment by edcarroll** [comment]
`0.9.3` is now live with a fix for this. This was actually happening due to how decorators are compiled into JS, since when you annotate something it keeps it's type ready to be accessed. Since `ModalTemplate` was a type, it was erased and so didn't exist at runtime. I've changed `ModalTemplate` to be an `abstract class` so that it still exists at runtime and no longer will cause this warning. Thanks for your patience!!

**Comment by dev-fullstacktechnology** [comment]
This is the snippet for I want feature available in our project.

**Comment by edcarroll** [comment]
@dev-fullstacktechnology I see what you mean, essentially an option for it to not remove the labels from the list.

Could you please open a separate issue as a feature request so I can track it there and get it into a release?

**Comment by dev-fullstacktechnology** [comment]
ok, That is good for us
