### ISSUE TITLE
Replace camel-case directives names to kebab-case please

### ISSUE THREAD

**Issue by pomkalk** [edcarroll/ng2-semantic-ui#283]
Replace camel-case directives selectors to kebab-case please, cuz it's do some problems sometimes
for example: [suiDropdown] to [sui-dropdown]

**Comment by edcarroll** [comment]
Hi there, thank you for your suggestion.

So the library uses lower camel case for these two things essentially because the official Angular style guide recommends it, [here](https://angular.io/guide/styleguide#style-03-04) and [here](https://angular.io/guide/styleguide#style-02-06).

There are parts of the code base that don't follow the styleguide, but those are mostly internal parts of the code that don't get exposed publically.

I'm also somewhat loath to change it because regardless of its correctness, it's a massive breaking change for **all** users of the library and would require a large upgrade procedure to update.

I hope that answers why we won't be doing that sufficiently 😄 Let me know if you have any further queries!
