### ISSUE TITLE
optionsLookup input missing in SuiSelectBase?

### ISSUE THREAD

**Issue by loudandwicked** [edcarroll/ng2-semantic-ui#47]
Since you separated local and remote options in search service, there should probably be optionsLookup input in SuiSelectBase to use remote options from a promise? Or maybe a detection of options type in SuiSelectBase?

Any way, as I can see, it is currently impossible to use remote options in `<sui-select>`.

**Comment by edcarroll** [comment]
This is currently by design - the difficulty with having remote options is that the select component needs to know what items are available in order to work correctly with ngModel when using `valueField`. If you can get a PR with it working consistently with ngModel, I'd be happy to take a look, but for now will leave it as is.

**Comment by loudandwicked** [comment]
Oh, yes, I can remember this didn't work with valueField before, and I had to have comparable value in options and ngModel in order to get it to work. Will dive into this and send a PR if I find a working solution. I really need this functionality in my UI :)

**Comment by loudandwicked** [comment]
I have an idea, but it seems a bit hackish, I would like to know your opinion about it.

In a lookup function we could differentiate between a query (detect a string maybe?) and an initial value request (is an object with valueField property?), and make two different API request. Maybe we could use an extra input for the initialization lookup function, so it's not that hackish?

Another option we could allow (to minimize API requests) is setting a selected item through ngModel, use it when initializing, and then setting a ngModel value to a value from valueField.

What do you think?

**Comment by edcarroll** [comment]
I've been having a think and I think that the 2nd option isn't ideal because the value of `ngModel` shouldn't really change based on input - it's incredibly counter intuitive. I prefer the 1st option, and I think 2 API requests is required at a minimum, because the select is looking up values based on a completely different field when searching, one who's value is unknown when using `valueField` and `ngModel`.

Rather than adding an extra property, I wonder if we can add an optional parameter to the lookup function itself, changing it's signature to:

```ts
type LookupFn<T, U> = (query:string, initial?:U) => T;
```

So that the function itself checks if the 2nd parameter is set, then returns it.

Thoughts?

**Comment by loudandwicked** [comment]
Yes, adding an extra parameter to a lookup function is way better solution. And I just remembered, we don't really need that 2nd awfully hackish solution to minimize API requests. If I have initial value already available in a model or anywhere else, I can just feed that value when resolving a promise in the lookup function.

**Comment by edcarroll** [comment]
Reopening as this is being added to the library 😄

**Comment by edcarroll** [comment]
This is now live in `0.6.0`. Thank you for your help with this!
