### ISSUE TITLE
Suggestion : System.config.js - components imports

### ISSUE THREAD

**Issue by mmazloum** [edcarroll/ng2-semantic-ui#5]
I saw you were doing something like in the Demo : 
import {ACCORDION_DIRECTIVES} from '../../../../components/accordion';

I saw in new jumpstart tutorials that they have a file called system.config.js, in this file I added 2 lines in my project : 
  // map tells the System loader where to look for things
  var map = {
     ...,
    'ng2-semantic-ui':            'node_modules/ng2-semantic-ui'
  };

and

  var packages = {
....
    'ng2-semantic-ui':            { defaultExtension: 'js' }
  };

Then I could Import your components like : 
import { Select } from 'ng2-semantic-ui/components/select';

Just to let you know ;-)

**Comment by edcarroll** [comment]
Ah! In the demo, the components are actually imported with 'ng2-semantic-ui/ng2-semantic-ui', the relative paths are for when I am developing using the demo directly. Since it is hosted by github pages, it isn't really feasible to have a node_modules folder with everything in, so I stick to using the bundle :)

**Comment by mmazloum** [comment]
ok ;-) that was just to help since I've had issues importing other packages
and I solved it like that

2016-05-20 1:13 GMT+02:00 Edward Carroll <notifications@github.com>:
