### ISSUE TITLE
Table Component? 

### ISSUE THREAD

**Issue by jaycdave88** [edcarroll/ng2-semantic-ui#67]
Is there work for a table component for the CSS and js?

**Comment by GregOnNet** [comment]
Hi,

there is no plan to do this yet.
Can you explain what benefit a table component would bring to your project?

**Comment by jaycdave88** [comment]
Well, since the semantic ui main install has a dependency on jQuery for its functionality - I turned to ng2-semantic-ui but it seems to have many components... besides table, are there plans to add it?

**Comment by GregOnNet** [comment]
Hey,

like I said we do not plan to bring up a table component yet.
Nevertheless I am very interested in the benefit you expect from such a component.

What is the reason why simpy applying the CSS styles of SemanticUI do not satisfy you?

**Comment by jaycdave88** [comment]
I am planning on using Semantic-UI in an Angular 4 application and updating the Angular 4 application to the latest version later on. Currently, I have the application set up using Webpack - I wanted to see if Semantic-UI could work in an Angular 4 project.

**Comment by edcarroll** [comment]
Hi there, so essentially, this project is a rewrite of the Semantic UI components that leverage jQuery in pure Angular. In order to keep the scope manageable, it relies on plain CSS as much as possible, hence why a lot of components, despite using Angular, still rely on the user adding classes for visual functionality (see [Accordion](https://edcarroll.github.io/ng2-semantic-ui/#/components/accordion)). Therefore, we don't plan to add any components that don't require javascript - using just the [Table](https://semantic-ui.com/collections/table.html) CSS classes alone will cover all of the functionality Semantic UI already provides. I hope that all makes sense!

**Comment by mvcoding** [comment]
It would be useful to have the [sortable table variant](https://semantic-ui.com/collections/table.html#sortable) from SUI though which relies on jQuery.

**Comment by jmls** [comment]
yeah, I've just hit this as well - the css is all well and good, but I need to be able to sort the data

**Comment by ChrisWun** [comment]
Me aswell. I want to sort the data in tables.
