### ISSUE TITLE
Always visible Sidebar

### ISSUE THREAD

**Issue by mcosta74** [edcarroll/ng2-semantic-ui#89]
Hi,

started to use your library a couple of days ago but I cannot find a way to have an "always visible" sidebar.
I want to avoid that clicking on the sibling contents the sidebar close

Here my sample code
```html
<sui-sidebar-container class="ui segment">
  <sui-sidebar class="blue inverted vertical menu" [(isVisible)]="barVisible">
  </sui-sidebar>
  <sui-sidebar-sibling [isDimmedWhenVisible]="false">
    <div class="ui raised segment">
      Hello {{ title }}
    </div>
  </sui-sidebar-sibling>
</sui-sidebar-container>
```

Is it possible or should I write a custom CSS ??

**Comment by edcarroll** [comment]
So the problem here is that Semantic UI doesn't include a way (CSS wise) of having a menu both able to pop out, and be visible all the time.

Instead, what they do and what seems to work best is to have a hidden sidebar, as well as a visible one, and just add a CSS rule that says the always visible one disappears when the screen is smaller than a certain width.

The demo application does it in this way, by having a dedicated sidebar component that displays the contents of the sidebar, like so:

```html
<sui-sidebar-container>
    <sui-sidebar class="vertical inverted" transition="uncover" direction="left" #sidebar>
        <demo-sidebar (onItemSelected)="sidebar.close()"></demo-sidebar>
    </sui-sidebar>
    <sui-sidebar-sibling [isDimmedWhenVisible]="true">
        <div class="full height">
            <div class="toc">
                <div class="ui vertical inverted menu">
                    <demo-sidebar></demo-sidebar>
                </div>
            </div>
            <div class="article">
                <div class="ui top attached inverted menu">
                    <a class="launch icon item" (click)="sidebar.open()">
                        <i class="content icon"></i>
                    </a>
                </div>
                <router-outlet></router-outlet>
            </div>
        </div>
    </sui-sidebar-sibling>
</sui-sidebar-container>
```

As Semantic UI doesn't appear to have a CSS rule for this, and it is a relatively complex thing to make work whilst retaining the responsive traits of the sidebar, it won't be a feature that will be added to the library - so the above will remain the way to do it.

Hope this has helped 😄

**Comment by mcosta74** [comment]
thanks, got it.

I'll use the demo approach
