### ISSUE TITLE
Error with SystemJS

### ISSUE THREAD

**Issue by slavik990** [edcarroll/ng2-semantic-ui#91]
Hi. I use `ng2-semantic-ui` with SytemJS and configured it like described in docs - for version `0.6.5` it works great, but after I migrated to `0.8.1` got error
```
(SystemJS) Cannot set property 'true' of undefined
	TypeError: Cannot set property 'true' of undefined
	    at eval (http://localhost:5555/node_modules/ng2-semantic-ui/bundles/ng2-semantic-ui.umd.min.js:3:185)
	    at Object.eval (http://localhost:5555/node_modules/ng2-semantic-ui/bundles/ng2-semantic-ui.umd.min.js:3:188)
```

**Comment by edcarroll** [comment]
I've investigated this a bit further and it looks to be due to the fact that the `web-animations-js` doesn't work with strict mode (and thus rollup at all!).

Before I move the polyfill out of the bundle, could you please try the attached bundle and let me know if you have the same error?

[ng2-semantic-ui.umd.min.zip](https://github.com/edcarroll/ng2-semantic-ui/files/1055388/ng2-semantic-ui.umd.min.zip)

**Comment by edcarroll** [comment]
`0.8.2` fixes this issue. Please do read [the release notes](https://github.com/edcarroll/ng2-semantic-ui/releases/tag/v0.8.2) to ensure the breaking change introduced doesn't affect you.
